language: node_js
node_js:
  - '8'
  - v12
  - v10
  - v8
cache:
  directories:
  - node_modules
after_script: cat ./coverage/lcov.info | coveralls
jobs:
  include:
    - stage: npm release
      node_js: "8"
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        api_key: $NPM_API_KEY
        on: deploy-npm-release